import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "Facebook Feed - Image Ads",
    description: "Single image ads in the main Facebook feed.",
    adType: "display",
    placement: "feed",
    format: "1200x628",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 50000,
    cpmEstimate: 7.5,
    cpcEstimate: 0.45,
    estimatedReach: 1000000,
    avgCtr: 0.028,
    avgConversion: 0.015,
    targetingOptions: {
      demographics: ["age", "gender", "location", "language"],
      interests: ["shopping", "technology", "fashion", "sports"],
      behaviors: ["online shoppers", "mobile users", "frequent travelers"],
    },
  },
  {
    title: "Facebook Feed - Video Ads",
    description: "Video ads in the main feed with autoplay.",
    adType: "video",
    placement: "feed",
    format: "4:5 or 1:1",
    pricingModel: "CPM" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 9.2,
    cpcEstimate: 0.38,
    estimatedReach: 800000,
    avgCtr: 0.035,
    avgConversion: 0.018,
    targetingOptions: {
      demographics: ["age", "gender", "location"],
      interests: ["entertainment", "music", "movies"],
      behaviors: ["video viewers", "engaged shoppers"],
    },
  },
  {
    title: "Facebook Stories Ads",
    description: "Full-screen vertical ads in Facebook Stories.",
    adType: "stories",
    placement: "stories",
    format: "9:16 vertical",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 25000,
    cpmEstimate: 5.8,
    cpcEstimate: 0.32,
    estimatedReach: 500000,
    avgCtr: 0.042,
    avgConversion: 0.012,
    targetingOptions: {
      demographics: ["age", "gender", "location"],
      interests: ["fashion", "lifestyle", "travel"],
      behaviors: ["stories viewers", "mobile-first users"],
    },
  },
  {
    title: "Facebook Reels Ads",
    description: "Short-form video ads in Facebook Reels.",
    adType: "video",
    placement: "reels",
    format: "9:16 vertical",
    pricingModel: "CPM" as PricingModel,
    minBudget: 10,
    maxBudget: 50000,
    cpmEstimate: 6.5,
    cpcEstimate: 0.28,
    estimatedReach: 600000,
    avgCtr: 0.048,
    avgConversion: 0.014,
    targetingOptions: {
      demographics: ["age 18-34", "gender", "location"],
      interests: ["entertainment", "gaming", "music"],
      behaviors: ["reels viewers", "trend followers"],
    },
  },
  {
    title: "Facebook Marketplace Ads",
    description: "Ads in Facebook Marketplace.",
    adType: "display",
    placement: "marketplace",
    format: "1200x628",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 20000,
    cpmEstimate: 4.2,
    cpcEstimate: 0.52,
    estimatedReach: 300000,
    avgCtr: 0.025,
    avgConversion: 0.022,
    targetingOptions: {
      demographics: ["location", "age"],
      interests: ["shopping", "deals", "local services"],
      behaviors: ["marketplace browsers", "online shoppers"],
    },
  },
  {
    title: "Facebook Right Column Ads",
    description: "Desktop-only ads in the right sidebar.",
    adType: "display",
    placement: "right_column",
    format: "1200x628",
    pricingModel: "CPC" as PricingModel,
    minBudget: 3,
    maxBudget: 10000,
    cpmEstimate: 2.8,
    cpcEstimate: 0.65,
    estimatedReach: 200000,
    avgCtr: 0.015,
    avgConversion: 0.02,
    targetingOptions: {
      demographics: ["desktop users", "age", "location"],
      interests: ["business", "technology"],
      behaviors: ["frequent online buyers"],
    },
  },
  {
    title: "Instagram Feed - Image Ads",
    description: "Single image ads in Instagram feed.",
    adType: "display",
    placement: "instagram_feed",
    format: "1080x1080",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 75000,
    cpmEstimate: 8.5,
    cpcEstimate: 0.55,
    estimatedReach: 900000,
    avgCtr: 0.032,
    avgConversion: 0.016,
    targetingOptions: {
      demographics: ["age 18-44", "gender", "location"],
      interests: ["fashion", "beauty", "lifestyle", "food"],
      behaviors: ["instagram shoppers", "influencer followers"],
    },
  },
  {
    title: "Instagram Stories Ads",
    description: "Full-screen vertical ads in Instagram Stories.",
    adType: "stories",
    placement: "instagram_stories",
    format: "9:16 vertical",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 50000,
    cpmEstimate: 6.2,
    cpcEstimate: 0.35,
    estimatedReach: 700000,
    avgCtr: 0.045,
    avgConversion: 0.014,
    targetingOptions: {
      demographics: ["age 18-34", "gender", "location"],
      interests: ["fashion", "beauty", "travel"],
      behaviors: ["stories viewers", "swipe-up users"],
    },
  },
  {
    title: "Instagram Reels Ads",
    description: "Short-form video ads in Instagram Reels.",
    adType: "video",
    placement: "instagram_reels",
    format: "9:16 vertical",
    pricingModel: "CPM" as PricingModel,
    minBudget: 10,
    maxBudget: 60000,
    cpmEstimate: 7.0,
    cpcEstimate: 0.30,
    estimatedReach: 800000,
    avgCtr: 0.052,
    avgConversion: 0.013,
    targetingOptions: {
      demographics: ["age 18-30", "gender", "location"],
      interests: ["entertainment", "music", "dance", "fashion"],
      behaviors: ["reels creators", "trend followers"],
    },
  },
  {
    title: "Instagram Explore Ads",
    description: "Ads in Instagram Explore feed.",
    adType: "display",
    placement: "instagram_explore",
    format: "1080x1080",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 30000,
    cpmEstimate: 5.5,
    cpcEstimate: 0.42,
    estimatedReach: 400000,
    avgCtr: 0.038,
    avgConversion: 0.015,
    targetingOptions: {
      demographics: ["age", "gender", "location"],
      interests: ["discovery", "new brands", "trending"],
      behaviors: ["explore users", "content discoverers"],
    },
  },
];

export class FacebookScraper extends BaseScraper {
  platformName = "Facebook Ads";
  platformType = "SOCIAL_MEDIA";
  sourceUrl = "https://www.facebook.com/business/ads-guide";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "fb");
  }
}
