import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "Google Search Ads - Text",
    description: "Text ads at the top of Google search results.",
    adType: "search",
    placement: "search_results",
    format: "text",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 45.0,
    cpcEstimate: 2.5,
    estimatedReach: 5000000,
    avgCtr: 0.035,
    avgConversion: 0.038,
    targetingOptions: { keywords: true, location: true, device: true, schedule: true, audiences: ["in-market", "affinity", "custom intent"] },
  },
  {
    title: "Google Display Network - Banner Ads",
    description: "Banner ads across millions of websites.",
    adType: "display",
    placement: "display_network",
    format: "300x250, 728x90, 160x600",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 50000,
    cpmEstimate: 2.8,
    cpcEstimate: 0.45,
    estimatedReach: 10000000,
    avgCtr: 0.008,
    avgConversion: 0.012,
    targetingOptions: { topics: true, placements: true, demographics: true, remarketing: true },
  },
  {
    title: "Google Display Network - Responsive Display Ads",
    description: "AI-optimized responsive ads that auto-adjust to fit any space.",
    adType: "display",
    placement: "display_network",
    format: "responsive",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 40000,
    cpmEstimate: 3.2,
    cpcEstimate: 0.52,
    estimatedReach: 8000000,
    avgCtr: 0.012,
    avgConversion: 0.015,
    targetingOptions: { topics: true, demographics: true, remarketing: true, similar_audiences: true },
  },
  {
    title: "YouTube TrueView In-Stream Ads",
    description: "Skippable video ads before or during YouTube videos.",
    adType: "video",
    placement: "youtube_instream",
    format: "video 16:9",
    pricingModel: "CPV" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 12.5,
    cpcEstimate: 0.08,
    estimatedReach: 2000000,
    avgCtr: 0.065,
    avgConversion: 0.018,
    targetingOptions: { demographics: true, interests: true, topics: true, placements: true, keywords: true },
  },
  {
    title: "YouTube Bumper Ads",
    description: "6-second non-skippable video ads.",
    adType: "video",
    placement: "youtube_bumper",
    format: "video 6s",
    pricingModel: "CPM" as PricingModel,
    minBudget: 10,
    maxBudget: 75000,
    cpmEstimate: 8.5,
    cpcEstimate: null,
    estimatedReach: 3000000,
    avgCtr: 0.025,
    avgConversion: 0.008,
    targetingOptions: { demographics: true, interests: true, topics: true },
  },
  {
    title: "YouTube Discovery Ads",
    description: "Video ads in YouTube search results and related videos.",
    adType: "video",
    placement: "youtube_discovery",
    format: "thumbnail + text",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 30000,
    cpmEstimate: 15.0,
    cpcEstimate: 0.25,
    estimatedReach: 1500000,
    avgCtr: 0.045,
    avgConversion: 0.022,
    targetingOptions: { keywords: true, topics: true, interests: true },
  },
  {
    title: "Google Shopping Ads",
    description: "Product listing ads with images and prices.",
    adType: "shopping",
    placement: "search_results",
    format: "product listing",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 150000,
    cpmEstimate: 25.0,
    cpcEstimate: 0.85,
    estimatedReach: 4000000,
    avgCtr: 0.082,
    avgConversion: 0.035,
    targetingOptions: { product_feed: true, location: true, device: true },
  },
  {
    title: "Google Performance Max",
    description: "AI-driven campaign across all Google properties.",
    adType: "multi-format",
    placement: "all_google",
    format: "responsive",
    pricingModel: "CPC" as PricingModel,
    minBudget: 20,
    maxBudget: 200000,
    cpmEstimate: 18.0,
    cpcEstimate: 1.2,
    estimatedReach: 15000000,
    avgCtr: 0.042,
    avgConversion: 0.028,
    targetingOptions: { audience_signals: true, goals: true, assets: true },
  },
  {
    title: "Google App Install Ads",
    description: "Ads promoting app installs across Search, Play, YouTube, and Display.",
    adType: "app_install",
    placement: "multi_platform",
    format: "responsive",
    pricingModel: "CPI" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 8.0,
    cpcEstimate: 1.5,
    estimatedReach: 5000000,
    avgCtr: 0.028,
    avgConversion: 0.045,
    targetingOptions: { demographics: true, interests: true, similar_apps: true },
  },
  {
    title: "Google Local Services Ads",
    description: "Ads for local service providers. Pay per lead.",
    adType: "local",
    placement: "search_results",
    format: "local listing",
    pricingModel: "CPA" as PricingModel,
    minBudget: 50,
    maxBudget: 50000,
    cpmEstimate: null,
    cpcEstimate: null,
    estimatedReach: 500000,
    avgCtr: 0.055,
    avgConversion: 0.12,
    targetingOptions: { service_area: true, service_type: true, schedule: true },
  },
];

export class GoogleAdsScraper extends BaseScraper {
  platformName = "Google Ads";
  platformType = "SEARCH_ENGINE";
  sourceUrl = "https://ads.google.com/home/resources/";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "google");
  }
}
