import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "LinkedIn Sponsored Content - Single Image",
    description: "Native ads in the LinkedIn feed with a single image.",
    adType: "display",
    placement: "feed",
    format: "1200x627 image",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 35.0,
    cpcEstimate: 5.5,
    estimatedReach: 850000,
    avgCtr: 0.045,
    avgConversion: 0.025,
    targetingOptions: { job_title: true, company_size: true, industry: true, seniority: true, skills: true, groups: true },
  },
  {
    title: "LinkedIn Sponsored Content - Carousel",
    description: "Multi-image carousel ads for showcasing multiple products or features.",
    adType: "carousel",
    placement: "feed",
    format: "carousel 1080x1080",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 80000,
    cpmEstimate: 38.0,
    cpcEstimate: 6.0,
    estimatedReach: 750000,
    avgCtr: 0.052,
    avgConversion: 0.028,
    targetingOptions: { job_title: true, company_size: true, industry: true, interests: true },
  },
  {
    title: "LinkedIn Sponsored Content - Video",
    description: "Native video ads in the LinkedIn feed.",
    adType: "video",
    placement: "feed",
    format: "video 16:9",
    pricingModel: "CPV" as PricingModel,
    minBudget: 10,
    maxBudget: 120000,
    cpmEstimate: 45.0,
    cpcEstimate: 8.0,
    estimatedReach: 600000,
    avgCtr: 0.065,
    avgConversion: 0.022,
    targetingOptions: { job_title: true, company_size: true, industry: true, seniority: true },
  },
  {
    title: "LinkedIn Sponsored InMail",
    description: "Direct messages to LinkedIn inboxes.",
    adType: "message",
    placement: "inbox",
    format: "message + CTA",
    pricingModel: "CPC" as PricingModel,
    minBudget: 25,
    maxBudget: 50000,
    cpmEstimate: 0,
    cpcEstimate: 0.5,
    estimatedReach: 200000,
    avgCtr: 0.35,
    avgConversion: 0.065,
    targetingOptions: { job_title: true, company: true, seniority: true, account_targeting: true },
  },
  {
    title: "LinkedIn Text Ads",
    description: "Simple text ads on desktop right rail.",
    adType: "text",
    placement: "right_rail",
    format: "text + 50x50 image",
    pricingModel: "CPC" as PricingModel,
    minBudget: 2,
    maxBudget: 20000,
    cpmEstimate: 8.0,
    cpcEstimate: 3.5,
    estimatedReach: 500000,
    avgCtr: 0.015,
    avgConversion: 0.018,
    targetingOptions: { job_title: true, industry: true, location: true },
  },
  {
    title: "LinkedIn Dynamic Ads - Follower",
    description: "Personalized ads to grow company page followers.",
    adType: "dynamic",
    placement: "right_rail",
    format: "dynamic 100x100",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 30000,
    cpmEstimate: 12.0,
    cpcEstimate: 4.0,
    estimatedReach: 400000,
    avgCtr: 0.025,
    avgConversion: 0.035,
    targetingOptions: { job_title: true, company_size: true, industry: true },
  },
  {
    title: "LinkedIn Lead Gen Forms",
    description: "Pre-filled lead forms attached to Sponsored Content.",
    adType: "lead_gen",
    placement: "feed",
    format: "form overlay",
    pricingModel: "CPA" as PricingModel,
    minBudget: 10,
    maxBudget: 75000,
    cpmEstimate: 42.0,
    cpcEstimate: 12.0,
    estimatedReach: 500000,
    avgCtr: 0.055,
    avgConversion: 0.12,
    targetingOptions: { job_title: true, company_size: true, industry: true, lookalike: true },
  },
  {
    title: "LinkedIn Conversation Ads",
    description: "Interactive message ads with multiple CTAs.",
    adType: "conversation",
    placement: "inbox",
    format: "interactive message",
    pricingModel: "CPC" as PricingModel,
    minBudget: 20,
    maxBudget: 60000,
    cpmEstimate: 0,
    cpcEstimate: 0.6,
    estimatedReach: 180000,
    avgCtr: 0.42,
    avgConversion: 0.072,
    targetingOptions: { job_title: true, company: true, seniority: true, interests: true },
  },
];

export class LinkedInScraper extends BaseScraper {
  platformName = "LinkedIn Ads";
  platformType = "SOCIAL_MEDIA";
  sourceUrl = "https://business.linkedin.com/marketing-solutions/ads";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "linkedin");
  }
}
