import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "Outbrain Standard Native",
    description: "Content recommendations on premium publishers.",
    adType: "native",
    placement: "content_feed",
    format: "image + headline",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 2.8,
    cpcEstimate: 0.38,
    estimatedReach: 8000000,
    avgCtr: 0.009,
    avgConversion: 0.016,
    targetingOptions: { publishers: true, location: true, device: true, interests: true, contextual: true },
  },
  {
    title: "Outbrain Clip - Video",
    description: "Native video ads in content feeds.",
    adType: "video",
    placement: "content_feed",
    format: "video 16:9",
    pricingModel: "CPV" as PricingModel,
    minBudget: 20,
    maxBudget: 120000,
    cpmEstimate: 9.0,
    cpcEstimate: 0.15,
    estimatedReach: 4000000,
    avgCtr: 0.028,
    avgConversion: 0.014,
    targetingOptions: { publishers: true, location: true, interests: true },
  },
  {
    title: "Outbrain Carousel",
    description: "Multi-image carousel in native placements.",
    adType: "carousel",
    placement: "content_feed",
    format: "carousel cards",
    pricingModel: "CPC" as PricingModel,
    minBudget: 15,
    maxBudget: 80000,
    cpmEstimate: 3.5,
    cpcEstimate: 0.45,
    estimatedReach: 5000000,
    avgCtr: 0.014,
    avgConversion: 0.02,
    targetingOptions: { publishers: true, interests: true, device: true },
  },
  {
    title: "Outbrain Click-to-Watch Video",
    description: "Video ads that play on user click.",
    adType: "video",
    placement: "click_to_play",
    format: "thumbnail + video",
    pricingModel: "CPV" as PricingModel,
    minBudget: 25,
    maxBudget: 100000,
    cpmEstimate: 12.0,
    cpcEstimate: 0.08,
    estimatedReach: 3000000,
    avgCtr: 0.045,
    avgConversion: 0.018,
    targetingOptions: { publishers: true, interests: true, location: true },
  },
  {
    title: "Outbrain Smartfeed",
    description: "AI-curated infinite scroll feed.",
    adType: "native",
    placement: "smartfeed",
    format: "standard native",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 75000,
    cpmEstimate: 3.2,
    cpcEstimate: 0.42,
    estimatedReach: 6000000,
    avgCtr: 0.012,
    avgConversion: 0.019,
    targetingOptions: { contextual: true, interests: true, location: true },
  },
  {
    title: "Outbrain Brand Studio",
    description: "Custom branded content experiences.",
    adType: "branded_content",
    placement: "premium",
    format: "rich media",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 5000,
    maxBudget: 150000,
    cpmEstimate: 15.0,
    cpcEstimate: undefined,
    estimatedReach: 2000000,
    avgCtr: 0.035,
    avgConversion: 0.025,
    targetingOptions: { premium_publishers: true, interests: true },
  },
  {
    title: "Outbrain Conversion Bid Strategy",
    description: "Automated bidding optimized for conversions.",
    adType: "native",
    placement: "conversion_optimized",
    format: "standard native",
    pricingModel: "CPA" as PricingModel,
    minBudget: 50,
    maxBudget: 100000,
    cpmEstimate: 6.0,
    cpcEstimate: 0.55,
    estimatedReach: 5000000,
    avgCtr: 0.018,
    avgConversion: 0.038,
    targetingOptions: { conversion_goal: true, publishers: true, lookalike: true },
  },
  {
    title: "Outbrain Native In-Article",
    description: "Ads placed within article body.",
    adType: "native",
    placement: "in_article",
    format: "in-content native",
    pricingModel: "CPM" as PricingModel,
    minBudget: 20,
    maxBudget: 90000,
    cpmEstimate: 7.5,
    cpcEstimate: 0.65,
    estimatedReach: 3500000,
    avgCtr: 0.025,
    avgConversion: 0.022,
    targetingOptions: { contextual: true, publishers: true, location: true },
  },
];

export class OutbrainScraper extends BaseScraper {
  platformName = "Outbrain";
  platformType = "NATIVE_ADS";
  sourceUrl = "https://www.outbrain.com";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "outbrain");
  }
}
