import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "Pinterest Standard Pins",
    description: "Promoted Pins in feeds and search.",
    adType: "display",
    placement: "feed",
    format: "1000x1500 image",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 50000,
    cpmEstimate: 4.5,
    cpcEstimate: 0.45,
    estimatedReach: 3500000,
    avgCtr: 0.028,
    avgConversion: 0.035,
    targetingOptions: { interests: true, keywords: true, demographics: true, actalike_audiences: true },
  },
  {
    title: "Pinterest Video Pins",
    description: "Promoted video content in feeds with autoplay.",
    adType: "video",
    placement: "feed",
    format: "video 2:3 or 9:16",
    pricingModel: "CPV" as PricingModel,
    minBudget: 5,
    maxBudget: 75000,
    cpmEstimate: 6.0,
    cpcEstimate: 0.55,
    estimatedReach: 2800000,
    avgCtr: 0.035,
    avgConversion: 0.032,
    targetingOptions: { interests: true, keywords: true, demographics: true },
  },
  {
    title: "Pinterest Carousel Pins",
    description: "Multi-image carousel ads for product collections.",
    adType: "carousel",
    placement: "feed",
    format: "carousel 1000x1000",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 60000,
    cpmEstimate: 5.0,
    cpcEstimate: 0.5,
    estimatedReach: 2500000,
    avgCtr: 0.032,
    avgConversion: 0.038,
    targetingOptions: { interests: true, keywords: true, customer_lists: true },
  },
  {
    title: "Pinterest Shopping Ads",
    description: "Product catalog ads with pricing.",
    adType: "shopping",
    placement: "feed",
    format: "product catalog",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 100000,
    cpmEstimate: 5.5,
    cpcEstimate: 0.48,
    estimatedReach: 3000000,
    avgCtr: 0.042,
    avgConversion: 0.055,
    targetingOptions: { product_feed: true, retargeting: true, interests: true },
  },
  {
    title: "Pinterest Collections Ads",
    description: "Hero image with product thumbnails.",
    adType: "collection",
    placement: "feed",
    format: "hero + products",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 80000,
    cpmEstimate: 6.5,
    cpcEstimate: 0.6,
    estimatedReach: 2200000,
    avgCtr: 0.038,
    avgConversion: 0.048,
    targetingOptions: { product_feed: true, interests: true, demographics: true },
  },
  {
    title: "Pinterest Idea Ads",
    description: "Multi-page story format with videos, images, and lists.",
    adType: "story",
    placement: "feed",
    format: "multi-page story",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 40000,
    cpmEstimate: 5.5,
    cpcEstimate: 0.52,
    estimatedReach: 1800000,
    avgCtr: 0.045,
    avgConversion: 0.028,
    targetingOptions: { interests: true, keywords: true, engagement_audiences: true },
  },
  {
    title: "Pinterest Quiz Ads",
    description: "Interactive quiz format with personalized recommendations.",
    adType: "interactive",
    placement: "feed",
    format: "quiz card",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 30000,
    cpmEstimate: 7.0,
    cpcEstimate: 0.65,
    estimatedReach: 1200000,
    avgCtr: 0.058,
    avgConversion: 0.042,
    targetingOptions: { interests: true, demographics: true },
  },
];

export class PinterestScraper extends BaseScraper {
  platformName = "Pinterest Ads";
  platformType = "SOCIAL_MEDIA";
  sourceUrl = "https://ads.pinterest.com";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "pinterest");
  }
}
