import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "Reddit Promoted Posts - Image",
    description: "Native image ads in subreddit feeds and home.",
    adType: "display",
    placement: "feed",
    format: "image + headline",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 50000,
    cpmEstimate: 3.5,
    cpcEstimate: 0.55,
    estimatedReach: 2000000,
    avgCtr: 0.012,
    avgConversion: 0.018,
    targetingOptions: { subreddits: true, interests: true, communities: true, location: true, device: true },
  },
  {
    title: "Reddit Promoted Posts - Video",
    description: "Video ads in feeds with autoplay.",
    adType: "video",
    placement: "feed",
    format: "video 16:9",
    pricingModel: "CPV" as PricingModel,
    minBudget: 5,
    maxBudget: 75000,
    cpmEstimate: 5.0,
    cpcEstimate: 0.65,
    estimatedReach: 1800000,
    avgCtr: 0.018,
    avgConversion: 0.015,
    targetingOptions: { subreddits: true, interests: true, communities: true },
  },
  {
    title: "Reddit Promoted Posts - Carousel",
    description: "Multi-card carousel ads.",
    adType: "carousel",
    placement: "feed",
    format: "carousel cards",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 40000,
    cpmEstimate: 4.0,
    cpcEstimate: 0.6,
    estimatedReach: 1500000,
    avgCtr: 0.015,
    avgConversion: 0.02,
    targetingOptions: { subreddits: true, interests: true },
  },
  {
    title: "Reddit Conversation Ads",
    description: "Ads within comment threads.",
    adType: "native",
    placement: "comments",
    format: "comment style",
    pricingModel: "CPM" as PricingModel,
    minBudget: 10,
    maxBudget: 60000,
    cpmEstimate: 6.0,
    cpcEstimate: 0.8,
    estimatedReach: 1200000,
    avgCtr: 0.022,
    avgConversion: 0.025,
    targetingOptions: { subreddits: true, keywords: true, topics: true },
  },
  {
    title: "Reddit Takeover - Front Page",
    description: "Premium placement at top of Reddit homepage for 24 hours.",
    adType: "takeover",
    placement: "homepage",
    format: "banner + content",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 25000,
    maxBudget: 100000,
    cpmEstimate: 2.5,
    cpcEstimate: null,
    estimatedReach: 30000000,
    avgCtr: 0.008,
    avgConversion: 0.005,
    targetingOptions: { location: true },
  },
  {
    title: "Reddit Category Takeover",
    description: "Dominate a specific interest category.",
    adType: "takeover",
    placement: "category",
    format: "category banner",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 10000,
    maxBudget: 50000,
    cpmEstimate: 4.0,
    cpcEstimate: null,
    estimatedReach: 5000000,
    avgCtr: 0.015,
    avgConversion: 0.012,
    targetingOptions: { category: true, location: true },
  },
  {
    title: "Reddit Free-Form Ads",
    description: "Custom content ads with rich formatting.",
    adType: "native",
    placement: "feed",
    format: "rich text + media",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 30000,
    cpmEstimate: 4.5,
    cpcEstimate: 0.7,
    estimatedReach: 1000000,
    avgCtr: 0.02,
    avgConversion: 0.022,
    targetingOptions: { subreddits: true, interests: true, custom_audiences: true },
  },
  {
    title: "Reddit Product Ads",
    description: "E-commerce ads with product details.",
    adType: "shopping",
    placement: "feed",
    format: "product card",
    pricingModel: "CPC" as PricingModel,
    minBudget: 5,
    maxBudget: 50000,
    cpmEstimate: 5.0,
    cpcEstimate: 0.75,
    estimatedReach: 1500000,
    avgCtr: 0.025,
    avgConversion: 0.032,
    targetingOptions: { product_feed: true, subreddits: true, interests: true },
  },
];

export class RedditScraper extends BaseScraper {
  platformName = "Reddit Ads";
  platformType = "SOCIAL_MEDIA";
  sourceUrl = "https://ads.reddit.com";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "reddit");
  }
}
