import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "Snapchat Single Image/Video Ads",
    description: "Full-screen vertical ads between Stories.",
    adType: "display",
    placement: "stories",
    format: "1080x1920 image/video",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 100000,
    cpmEstimate: 3.5,
    cpcEstimate: 0.35,
    estimatedReach: 4000000,
    avgCtr: 0.018,
    avgConversion: 0.012,
    targetingOptions: { demographics: true, interests: true, behaviors: true, location: true, snap_audience_match: true },
  },
  {
    title: "Snapchat Story Ads",
    description: "Branded tile in Discover feed opening to 3-20 Snaps.",
    adType: "story",
    placement: "discover",
    format: "story collection",
    pricingModel: "CPM" as PricingModel,
    minBudget: 20,
    maxBudget: 150000,
    cpmEstimate: 8.0,
    cpcEstimate: 0.8,
    estimatedReach: 2500000,
    avgCtr: 0.045,
    avgConversion: 0.015,
    targetingOptions: { demographics: true, interests: true, custom_audiences: true },
  },
  {
    title: "Snapchat Collection Ads",
    description: "Shoppable product ads with 4 products.",
    adType: "collection",
    placement: "stories",
    format: "hero + 4 products",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 80000,
    cpmEstimate: 5.5,
    cpcEstimate: 0.55,
    estimatedReach: 2000000,
    avgCtr: 0.032,
    avgConversion: 0.028,
    targetingOptions: { product_catalog: true, interests: true, retargeting: true },
  },
  {
    title: "Snapchat Dynamic Ads",
    description: "Auto-generated ads from product catalog.",
    adType: "dynamic",
    placement: "stories",
    format: "dynamic product",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 4.5,
    cpcEstimate: 0.48,
    estimatedReach: 3500000,
    avgCtr: 0.025,
    avgConversion: 0.035,
    targetingOptions: { product_catalog: true, retargeting: true, lookalike: true },
  },
  {
    title: "Snapchat AR Lens Ads",
    description: "Sponsored AR lenses users can play with.",
    adType: "ar",
    placement: "camera",
    format: "AR lens",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 10000,
    maxBudget: 500000,
    cpmEstimate: 2.5,
    cpcEstimate: null,
    estimatedReach: 20000000,
    avgCtr: 0.12,
    avgConversion: 0.008,
    targetingOptions: { demographics: true, location: true },
  },
  {
    title: "Snapchat Filter Ads",
    description: "Location-based branded filters for events.",
    adType: "filter",
    placement: "camera",
    format: "geofilter overlay",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 5,
    maxBudget: 50000,
    cpmEstimate: 1.5,
    cpcEstimate: null,
    estimatedReach: 500000,
    avgCtr: 0.085,
    avgConversion: 0.005,
    targetingOptions: { location: true, time: true, geofence: true },
  },
  {
    title: "Snapchat Commercials",
    description: "Non-skippable 6-second video ads in premium content.",
    adType: "video",
    placement: "shows",
    format: "video 6s",
    pricingModel: "CPM" as PricingModel,
    minBudget: 50,
    maxBudget: 200000,
    cpmEstimate: 15.0,
    cpcEstimate: null,
    estimatedReach: 1500000,
    avgCtr: 0.065,
    avgConversion: 0.01,
    targetingOptions: { demographics: true, interests: true, content_categories: true },
  },
  {
    title: "Snapchat Spotlight Ads",
    description: "Ads in the Spotlight viral video feed.",
    adType: "video",
    placement: "spotlight",
    format: "vertical video",
    pricingModel: "CPM" as PricingModel,
    minBudget: 5,
    maxBudget: 75000,
    cpmEstimate: 4.0,
    cpcEstimate: 0.4,
    estimatedReach: 5000000,
    avgCtr: 0.022,
    avgConversion: 0.014,
    targetingOptions: { demographics: true, interests: true },
  },
];

export class SnapchatScraper extends BaseScraper {
  platformName = "Snapchat Ads";
  platformType = "SOCIAL_MEDIA";
  sourceUrl = "https://ads.snapchat.com";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "snapchat");
  }
}
