import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "Taboola Sponsored Content - Standard",
    description: "Native content recommendations on premium publisher sites.",
    adType: "native",
    placement: "content_discovery",
    format: "image + headline",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 100000,
    cpmEstimate: 2.5,
    cpcEstimate: 0.35,
    estimatedReach: 10000000,
    avgCtr: 0.008,
    avgConversion: 0.015,
    targetingOptions: { publishers: true, location: true, device: true, os: true, time_of_day: true, audience_segments: true },
  },
  {
    title: "Taboola Video Content",
    description: "Video ads in content recommendation widgets.",
    adType: "video",
    placement: "content_discovery",
    format: "video 16:9",
    pricingModel: "CPV" as PricingModel,
    minBudget: 20,
    maxBudget: 150000,
    cpmEstimate: 8.0,
    cpcEstimate: 0.12,
    estimatedReach: 5000000,
    avgCtr: 0.025,
    avgConversion: 0.012,
    targetingOptions: { publishers: true, location: true, interests: true },
  },
  {
    title: "Taboola Motion Ads",
    description: "Animated GIF-style ads in content widgets.",
    adType: "motion",
    placement: "content_discovery",
    format: "animated image",
    pricingModel: "CPC" as PricingModel,
    minBudget: 10,
    maxBudget: 75000,
    cpmEstimate: 3.0,
    cpcEstimate: 0.4,
    estimatedReach: 8000000,
    avgCtr: 0.012,
    avgConversion: 0.018,
    targetingOptions: { publishers: true, location: true, device: true },
  },
  {
    title: "Taboola High Impact Placements",
    description: "Premium positions at top of feed.",
    adType: "native",
    placement: "high_impact",
    format: "large image + text",
    pricingModel: "CPC" as PricingModel,
    minBudget: 50,
    maxBudget: 200000,
    cpmEstimate: 6.0,
    cpcEstimate: 0.65,
    estimatedReach: 3000000,
    avgCtr: 0.018,
    avgConversion: 0.022,
    targetingOptions: { premium_publishers: true, location: true, audience_segments: true },
  },
  {
    title: "Taboola Homepage Takeover",
    description: "Exclusive placement on publisher homepages.",
    adType: "takeover",
    placement: "homepage",
    format: "hero placement",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 5000,
    maxBudget: 100000,
    cpmEstimate: 4.0,
    cpcEstimate: null,
    estimatedReach: 15000000,
    avgCtr: 0.015,
    avgConversion: 0.008,
    targetingOptions: { publishers: true, time: true },
  },
  {
    title: "Taboola Attentive Audiences",
    description: "Target users based on attention metrics.",
    adType: "native",
    placement: "attention_targeting",
    format: "image + headline",
    pricingModel: "CPC" as PricingModel,
    minBudget: 20,
    maxBudget: 80000,
    cpmEstimate: 4.5,
    cpcEstimate: 0.55,
    estimatedReach: 4000000,
    avgCtr: 0.022,
    avgConversion: 0.028,
    targetingOptions: { attention_segments: true, interests: true, location: true },
  },
  {
    title: "Taboola Smartbid",
    description: "AI-optimized bidding for conversions.",
    adType: "native",
    placement: "smart_optimization",
    format: "standard native",
    pricingModel: "CPA" as PricingModel,
    minBudget: 50,
    maxBudget: 100000,
    cpmEstimate: 5.5,
    cpcEstimate: 0.5,
    estimatedReach: 6000000,
    avgCtr: 0.015,
    avgConversion: 0.035,
    targetingOptions: { conversion_goal: true, publishers: true, location: true },
  },
];

export class TaboolaScraper extends BaseScraper {
  platformName = "Taboola";
  platformType = "NATIVE_ADS";
  sourceUrl = "https://www.taboola.com";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "taboola");
  }
}
