import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "TikTok In-Feed Ads",
    description: "Native video ads in the For You feed.",
    adType: "video",
    placement: "for_you_feed",
    format: "9:16 vertical video",
    pricingModel: "CPM" as PricingModel,
    minBudget: 20,
    maxBudget: 100000,
    cpmEstimate: 10.0,
    cpcEstimate: 0.50,
    estimatedReach: 2000000,
    avgCtr: 0.065,
    avgConversion: 0.015,
    targetingOptions: {
      demographics: ["age 13-55", "gender", "location"],
      interests: ["entertainment", "gaming", "fashion", "beauty", "sports"],
      behaviors: ["video viewers", "creators", "engagers"],
      device: true,
    },
  },
  {
    title: "TikTok TopView Ads",
    description: "Premium full-screen ads when users open TikTok.",
    adType: "video",
    placement: "app_open",
    format: "9:16 vertical video up to 60s",
    pricingModel: "CPM" as PricingModel,
    minBudget: 50000,
    maxBudget: 500000,
    cpmEstimate: 35.0,
    cpcEstimate: 1.20,
    estimatedReach: 5000000,
    avgCtr: 0.12,
    avgConversion: 0.025,
    targetingOptions: { demographics: ["age", "gender", "location"], reach_frequency: true },
  },
  {
    title: "TikTok Brand Takeover",
    description: "Exclusive full-screen ad when users first open the app.",
    adType: "video",
    placement: "brand_takeover",
    format: "3-5s image or video",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 50000,
    maxBudget: 150000,
    cpmEstimate: 28.0,
    cpcEstimate: undefined,
    estimatedReach: 8000000,
    avgCtr: 0.08,
    avgConversion: 0.018,
    targetingOptions: { demographics: ["location"], exclusivity: "daily" },
  },
  {
    title: "TikTok Branded Hashtag Challenge",
    description: "Sponsored hashtag challenges encouraging user-generated content.",
    adType: "interactive",
    placement: "discover_page",
    format: "challenge + video",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 100000,
    maxBudget: 300000,
    cpmEstimate: 15.0,
    cpcEstimate: undefined,
    estimatedReach: 10000000,
    avgCtr: 0.085,
    avgConversion: 0.012,
    targetingOptions: { all_users: true, featured_placement: true },
  },
  {
    title: "TikTok Branded Effects",
    description: "Custom AR filters and effects users can apply to their videos.",
    adType: "interactive",
    placement: "effects_panel",
    format: "AR effect",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 80000,
    maxBudget: 200000,
    cpmEstimate: 12.0,
    cpcEstimate: undefined,
    estimatedReach: 3000000,
    avgCtr: 0.055,
    avgConversion: 0.008,
    targetingOptions: { effect_category: true, featured: true },
  },
  {
    title: "TikTok Spark Ads",
    description: "Boost organic TikTok posts or creator content.",
    adType: "native",
    placement: "for_you_feed",
    format: "organic post",
    pricingModel: "CPM" as PricingModel,
    minBudget: 20,
    maxBudget: 50000,
    cpmEstimate: 8.5,
    cpcEstimate: 0.35,
    estimatedReach: 1500000,
    avgCtr: 0.075,
    avgConversion: 0.018,
    targetingOptions: { demographics: true, interests: true, behaviors: true, lookalike: true },
  },
  {
    title: "TikTok Collection Ads",
    description: "Showcase multiple products with instant browsing.",
    adType: "shopping",
    placement: "for_you_feed",
    format: "video + product cards",
    pricingModel: "CPC" as PricingModel,
    minBudget: 50,
    maxBudget: 75000,
    cpmEstimate: 12.0,
    cpcEstimate: 0.65,
    estimatedReach: 1000000,
    avgCtr: 0.058,
    avgConversion: 0.032,
    targetingOptions: { demographics: true, shopping_behavior: true, product_categories: true },
  },
  {
    title: "TikTok Dynamic Showcase Ads",
    description: "Personalized product ads based on user behavior.",
    adType: "shopping",
    placement: "for_you_feed",
    format: "dynamic product video",
    pricingModel: "CPC" as PricingModel,
    minBudget: 50,
    maxBudget: 100000,
    cpmEstimate: 14.0,
    cpcEstimate: 0.55,
    estimatedReach: 800000,
    avgCtr: 0.068,
    avgConversion: 0.042,
    targetingOptions: { retargeting: true, product_catalog: true, purchase_intent: true },
  },
];

export class TikTokScraper extends BaseScraper {
  platformName = "TikTok Ads";
  platformType = "SOCIAL_MEDIA";
  sourceUrl = "https://ads.tiktok.com/help/";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "tiktok");
  }
}
