import { BaseScraper, ScraperResult, AdPlacement } from "./base-scraper";
import { PricingModel } from "@prisma/client";

const AD_PLACEMENTS: AdPlacement[] = [
  {
    title: "X Promoted Posts - Single Image",
    description: "Native tweet ads with single image in timeline and search.",
    adType: "display",
    placement: "timeline",
    format: "1200x675 image",
    pricingModel: "CPC" as PricingModel,
    minBudget: 1,
    maxBudget: 100000,
    cpmEstimate: 6.5,
    cpcEstimate: 0.75,
    estimatedReach: 2500000,
    avgCtr: 0.018,
    avgConversion: 0.012,
    targetingOptions: { interests: true, keywords: true, followers_lookalike: true, events: true, conversation_topics: true },
  },
  {
    title: "X Promoted Posts - Video",
    description: "Video ads in timeline with autoplay.",
    adType: "video",
    placement: "timeline",
    format: "video 16:9",
    pricingModel: "CPV" as PricingModel,
    minBudget: 1,
    maxBudget: 150000,
    cpmEstimate: 8.0,
    cpcEstimate: 0.5,
    estimatedReach: 3000000,
    avgCtr: 0.028,
    avgConversion: 0.015,
    targetingOptions: { interests: true, keywords: true, events: true, devices: true },
  },
  {
    title: "X Promoted Posts - Carousel",
    description: "Multi-image or video carousel ads.",
    adType: "carousel",
    placement: "timeline",
    format: "carousel 800x800",
    pricingModel: "CPC" as PricingModel,
    minBudget: 1,
    maxBudget: 80000,
    cpmEstimate: 7.0,
    cpcEstimate: 0.85,
    estimatedReach: 2000000,
    avgCtr: 0.022,
    avgConversion: 0.014,
    targetingOptions: { interests: true, keywords: true, hashtags: true },
  },
  {
    title: "X Amplify Pre-Roll",
    description: "Video ads before premium publisher content.",
    adType: "video",
    placement: "pre_roll",
    format: "video 15s max",
    pricingModel: "CPV" as PricingModel,
    minBudget: 50,
    maxBudget: 200000,
    cpmEstimate: 12.0,
    cpcEstimate: 0.1,
    estimatedReach: 1500000,
    avgCtr: 0.065,
    avgConversion: 0.018,
    targetingOptions: { content_categories: true, interests: true, demographics: true },
  },
  {
    title: "X Takeover - Timeline",
    description: "First ad of the day in user timelines.",
    adType: "takeover",
    placement: "timeline",
    format: "video or image",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 50000,
    maxBudget: 250000,
    cpmEstimate: 4.0,
    cpcEstimate: 0.4,
    estimatedReach: 50000000,
    avgCtr: 0.035,
    avgConversion: 0.008,
    targetingOptions: { location: true, interests: true },
  },
  {
    title: "X Takeover - Trend",
    description: "Promoted hashtag in Trending section.",
    adType: "trend",
    placement: "trending",
    format: "hashtag + creative",
    pricingModel: "FLAT_RATE" as PricingModel,
    minBudget: 100000,
    maxBudget: 500000,
    cpmEstimate: 3.0,
    cpcEstimate: null,
    estimatedReach: 80000000,
    avgCtr: 0.042,
    avgConversion: 0.005,
    targetingOptions: { location: true },
  },
  {
    title: "X App Install Ads",
    description: "Promoted posts with app install CTA.",
    adType: "app_install",
    placement: "timeline",
    format: "app card",
    pricingModel: "CPI" as PricingModel,
    minBudget: 5,
    maxBudget: 100000,
    cpmEstimate: 9.0,
    cpcEstimate: 2.5,
    estimatedReach: 2000000,
    avgCtr: 0.024,
    avgConversion: 0.045,
    targetingOptions: { interests: true, similar_apps: true, device_model: true },
  },
  {
    title: "X Website Clicks/Conversions",
    description: "Promoted posts optimized for website traffic.",
    adType: "website",
    placement: "timeline",
    format: "website card",
    pricingModel: "CPC" as PricingModel,
    minBudget: 1,
    maxBudget: 75000,
    cpmEstimate: 7.5,
    cpcEstimate: 0.95,
    estimatedReach: 1800000,
    avgCtr: 0.02,
    avgConversion: 0.022,
    targetingOptions: { interests: true, keywords: true, website_visitors: true },
  },
];

export class TwitterScraper extends BaseScraper {
  platformName = "Twitter/X Ads";
  platformType = "SOCIAL_MEDIA";
  sourceUrl = "https://ads.twitter.com";

  async scrape(): Promise<ScraperResult[]> {
    return this.buildResults(AD_PLACEMENTS, "twitter");
  }
}
